### ISSUE TITLE
Path problems for ergodox_ez/shine 

### ISSUE THREAD

**Issue by davidhbrown** [poulainpi/oryx-with-custom-qmk#6]
I think should be using the path ergodox_ez/m32u4/shine but that's still getting a path error when trying to upload; it does seem to compile:

```
...
Creating load file for flashing: .build/zsa_ergodox_ez_m32u4_shine_LvADM.hex                        [OK]
Copying zsa_ergodox_ez_m32u4_shine_LvADM.hex to qmk_firmware folder                                 [OK]
Checking file size of zsa_ergodox_ez_m32u4_shine_LvADM.hex                                          [OK]
 * The firmware size is fine - 22826/32256 (70%, 9430 bytes free)
Checking stack size of zsa_ergodox_ez_m32u4_shine_LvADM                                            
 * Available stack size: 1906 bytes

(Upload layout)
Run actions/upload-artifact@v4
  with:
    name: ergodox_ez_m32u4_shine_LvADM
    if-no-files-found: warn
    compression-level: 6
    overwrite: false
    include-hidden-files: false
Error: Input required and not supplied: path
```

My first attempt below was based on the false assumption that what I saw in the QMK firmware repository is what is being used here.  I jumped ahead from initializing the workflow to cloning to my local system and I see that the keyboards are in the zsa folder as well. I should probably just delete this and the rest, but perhaps someone else could avoid wasting their time the same way ;-}

_First attempt_
I have a Ergodox EZ "shine" from way before Sept '24 (Sticker says BATCH 4a; keyswitches are soldered) using the "teensy" MCU. As required by Oryx to make further changes, I have updated the layout to use QMK firmware version 24.

Because the firmware version is -ge 24, the keyboard path is prefixed with "zsa" and I see an error ```make: *** No rule to make target 'zsa/ergodox_ez/shine:LvADM'. Stop.``` at line 361 of the "Build the layout step" followed by ```Error: Input required and not supplied: path``` in the "Upload layout" step.

As of this writing, this keyboard seems to still be found in QMK's keyboards/ergodox_ez, folder, in subfolders "base" "glow" and "shine". [Link to repo](https://github.com/qmk/qmk_firmware/tree/master/keyboards/ergodox_ez)  There is no ergodox_ez/shine keyboard within the zsa folder.

This seems to be similar to issue #4 but I don't think I can just type a different path because of the zsa prefix.

I have attempted to patch my copy of the workflow file to simply set the keyboard_directory and make_prefix paths without zsa no matter what firmware:
```
      - name: Build the layout
        id: build-layout
        run: |
          keyboard_directory="qmk_firmware/keyboards"
          make_prefix=""

          # Copy layout files to the qmk folder
```
... but when I went to test this with ```ergodox_ez/shine``` as the path, I seem to have encountered some downtime for oryx.zsa.io which is giving 500s instead of source files (I checked via the web with other peoples' more recent layouts, too). 

Hadn't wanted to post this before I could really test what I think might be a fix, but I also don't want to lose what I've written up so far. Hope it can be helpful; I will try to update if I can get it to work by hacking on the workflow file.

**Comment by poulainpi** [comment]
You should indeed use ergodox_ez/m32u4/shine as the keyboard type. However, it seems the built firmware is not a .bin file but a .hex file instead. I just pushed a fix to upload the .hex firmware when needed.

Please try again and let me know if you encounter any further issues!

**Comment by davidhbrown** [comment]
Thank you so much! The action did complete :-) 
Now on to read the rest of your instructions and see if I can incorporate the code I wrote something like 7 years ago to control the status LEDs...

**Comment by poulainpi** [comment]
You’re very welcome!

Did you manage to flash the layout using the .hex file?

**Comment by davidhbrown** [comment]
Haven't tried, but I did confirm that the SHA-512 checksum for the hex file your workflow produces is the same as for the one I download from Oryx.

I hope to actually flash firmware soon, but as I have lost track of the build environment and hex file I made in 2019 (I do still have the code itself in my QMK fork). I wanted to try to update that code with respect to the changes to QMK since then. If I just flash the Oryx hex file, I'll  lose my custom status LED behavior until I can work through the rest of your instructions. And the updated QMK documentation.

**Comment by RKBK** [comment]
Hi! I just tried this tool. I got exactly the same type of path error, but for my ergodox_ez keyboard (neither shine nor glow). I forked the repo just about 15 minutes ago.

**Comment by poulainpi** [comment]
@RKBK It seems there was a small typo in the keyboard type you entered—you used ergox_ez instead of ergodox_ez. Correcting this should resolve the path error.

**Comment by RKBK** [comment]
Oh my. That's what I get for not being more careful. I will try adding a "d" right away. :-)

Many thanks!

**Comment by davidhbrown** [comment]
@poulainpi You're my hero for the week :-) It took me only about an hour of reading documentation and rethinking code to adapt my old work to this system... and it works! Thank you so much for doing and sharing this... not wanting to lose my custom status LEDs was a big reason I haven't upgraded to a Moonlander, so Erez might owe you a commission soon ;-)
